import './bootstrap';
import '../scss/custom.scss';
import '../scss/_home.scss';
import '../scss/_solucoes.scss';
import '../scss/_sobre-nos.scss';
import '../scss/nossos-clientes.scss';
import '../scss/contact_modal_1.scss';
import '../scss/_footer.scss';
import '../scss/_header.scss';
